# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '2dfullscreenwindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1059, 897)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(210, 10, 831, 421))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.graphicsView = QtWidgets.QGraphicsView(self.frame)
        self.graphicsView.setGeometry(QtCore.QRect(0, 0, 841, 421))
        self.graphicsView.setObjectName("graphicsView")
        self.tools2D = QtWidgets.QGroupBox(self.centralwidget)
        self.tools2D.setGeometry(QtCore.QRect(10, 0, 191, 141))
        self.tools2D.setObjectName("tools2D")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tools2D)
        self.verticalLayout.setObjectName("verticalLayout")
        self.allScreenBtn = QtWidgets.QPushButton(self.tools2D)
        self.allScreenBtn.setObjectName("allScreenBtn")
        self.verticalLayout.addWidget(self.allScreenBtn)
        self.alignmentLinesCheckBox = QtWidgets.QCheckBox(self.tools2D)
        self.alignmentLinesCheckBox.setObjectName("alignmentLinesCheckBox")
        self.verticalLayout.addWidget(self.alignmentLinesCheckBox)
        self.coordinatesCheckBox = QtWidgets.QCheckBox(self.tools2D)
        self.coordinatesCheckBox.setObjectName("coordinatesCheckBox")
        self.verticalLayout.addWidget(self.coordinatesCheckBox)
        self.tools3D = QtWidgets.QGroupBox(self.centralwidget)
        self.tools3D.setGeometry(QtCore.QRect(10, 140, 191, 341))
        self.tools3D.setObjectName("tools3D")
        self.mouseXYTextEdit = QtWidgets.QTextEdit(self.tools3D)
        self.mouseXYTextEdit.setGeometry(QtCore.QRect(10, 40, 171, 21))
        self.mouseXYTextEdit.setObjectName("mouseXYTextEdit")
        self.label_3 = QtWidgets.QLabel(self.tools3D)
        self.label_3.setGeometry(QtCore.QRect(10, 20, 101, 16))
        self.label_3.setObjectName("label_3")
        self.findStarBtn = QtWidgets.QPushButton(self.tools3D)
        self.findStarBtn.setGeometry(QtCore.QRect(10, 60, 171, 32))
        self.findStarBtn.setObjectName("findStarBtn")
        self.closestStarTextBrowser = QtWidgets.QTextBrowser(self.tools3D)
        self.closestStarTextBrowser.setGeometry(QtCore.QRect(10, 90, 171, 241))
        self.closestStarTextBrowser.setObjectName("closestStarTextBrowser")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(220, 430, 331, 51))
        self.groupBox.setObjectName("groupBox")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(0, 20, 91, 32))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(90, 20, 81, 32))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(180, 19, 141, 31))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1059, 22))
        self.menubar.setObjectName("menubar")
        self.menuSaveAs = QtWidgets.QMenu(self.menubar)
        self.menuSaveAs.setObjectName("menuSaveAs")
        self.menuStarStandard = QtWidgets.QMenu(self.menubar)
        self.menuStarStandard.setObjectName("menuStarStandard")
        self.menuDataset = QtWidgets.QMenu(self.menubar)
        self.menuDataset.setObjectName("menuDataset")
        self.backgroundMenu = QtWidgets.QMenu(self.menubar)
        self.backgroundMenu.setObjectName("backgroundMenu")
        MainWindow.setMenuBar(self.menubar)
        self.actionpng = QtWidgets.QAction(MainWindow)
        self.actionpng.setObjectName("actionpng")
        self.actionjpeg = QtWidgets.QAction(MainWindow)
        self.actionjpeg.setObjectName("actionjpeg")
        self.actionsvg = QtWidgets.QAction(MainWindow)
        self.actionsvg.setObjectName("actionsvg")
        self.action1 = QtWidgets.QAction(MainWindow)
        self.action1.setObjectName("action1")
        self.action2 = QtWidgets.QAction(MainWindow)
        self.action2.setObjectName("action2")
        self.action3 = QtWidgets.QAction(MainWindow)
        self.action3.setObjectName("action3")
        self.action4 = QtWidgets.QAction(MainWindow)
        self.action4.setObjectName("action4")
        self.actionBSC = QtWidgets.QAction(MainWindow)
        self.actionBSC.setObjectName("actionBSC")
        self.actionHipparcos = QtWidgets.QAction(MainWindow)
        self.actionHipparcos.setObjectName("actionHipparcos")
        self.actionNatrual = QtWidgets.QAction(MainWindow)
        self.actionNatrual.setObjectName("actionNatrual")
        self.actionPurple_sky = QtWidgets.QAction(MainWindow)
        self.actionPurple_sky.setObjectName("actionPurple_sky")
        self.actionGreyscale = QtWidgets.QAction(MainWindow)
        self.actionGreyscale.setObjectName("actionGreyscale")
        self.actionPrinter_friendly = QtWidgets.QAction(MainWindow)
        self.actionPrinter_friendly.setObjectName("actionPrinter_friendly")
        self.actionPrinter_greyscale = QtWidgets.QAction(MainWindow)
        self.actionPrinter_greyscale.setObjectName("actionPrinter_greyscale")
        self.menuSaveAs.addAction(self.actionpng)
        self.menuSaveAs.addAction(self.actionjpeg)
        self.menuSaveAs.addAction(self.actionsvg)
        self.menuStarStandard.addAction(self.action1)
        self.menuStarStandard.addAction(self.action2)
        self.menuStarStandard.addAction(self.action3)
        self.menuStarStandard.addAction(self.action4)
        self.menuDataset.addAction(self.actionBSC)
        self.menuDataset.addAction(self.actionHipparcos)
        self.backgroundMenu.addAction(self.actionNatrual)
        self.backgroundMenu.addAction(self.actionPurple_sky)
        self.backgroundMenu.addAction(self.actionGreyscale)
        self.backgroundMenu.addAction(self.actionPrinter_friendly)
        self.backgroundMenu.addAction(self.actionPrinter_greyscale)
        self.menubar.addAction(self.menuDataset.menuAction())
        self.menubar.addAction(self.menuStarStandard.menuAction())
        self.menubar.addAction(self.menuSaveAs.menuAction())
        self.menubar.addAction(self.backgroundMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tools2D.setTitle(_translate("MainWindow", "二维图选项"))
        self.allScreenBtn.setText(_translate("MainWindow", "回到主界面"))
        self.alignmentLinesCheckBox.setText(_translate("MainWindow", "有准线"))
        self.coordinatesCheckBox.setText(_translate("MainWindow", "有坐标"))
        self.tools3D.setTitle(_translate("MainWindow", "鼠标点击，找到附近的星星"))
        self.label_3.setText(_translate("MainWindow", "你点击的位置是："))
        self.findStarBtn.setText(_translate("MainWindow", "最近的星体"))
        self.groupBox.setTitle(_translate("MainWindow", " 缩放"))
        self.pushButton.setText(_translate("MainWindow", "放大"))
        self.pushButton_2.setText(_translate("MainWindow", "缩小"))
        self.label.setText(_translate("MainWindow", "当前比例：0.5"))
        self.menuSaveAs.setTitle(_translate("MainWindow", "2D预览另存为"))
        self.menuStarStandard.setTitle(_translate("MainWindow", "星等"))
        self.menuDataset.setTitle(_translate("MainWindow", " 导入数据集"))
        self.backgroundMenu.setTitle(_translate("MainWindow", "背景颜色"))
        self.actionpng.setText(_translate("MainWindow", "png"))
        self.actionjpeg.setText(_translate("MainWindow", "jpeg"))
        self.actionsvg.setText(_translate("MainWindow", "svg"))
        self.action1.setText(_translate("MainWindow", "1"))
        self.action2.setText(_translate("MainWindow", "2"))
        self.action3.setText(_translate("MainWindow", "3"))
        self.action4.setText(_translate("MainWindow", "4"))
        self.actionBSC.setText(_translate("MainWindow", "BSC"))
        self.actionBSC.setIconText(_translate("MainWindow", "BSC"))
        self.actionHipparcos.setText(_translate("MainWindow", "Hipparcos"))
        self.actionNatrual.setText(_translate("MainWindow", "Natrual"))
        self.actionPurple_sky.setText(_translate("MainWindow", "Purple sky"))
        self.actionGreyscale.setText(_translate("MainWindow", "Greyscale"))
        self.actionPrinter_friendly.setText(_translate("MainWindow", "Printer friendly"))
        self.actionPrinter_greyscale.setText(_translate("MainWindow", "Printer greyscale"))


