# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1231, 755)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tools2D = QtWidgets.QGroupBox(self.centralwidget)
        self.tools2D.setGeometry(QtCore.QRect(10, 207, 251, 241))
        self.tools2D.setObjectName("tools2D")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tools2D)
        self.verticalLayout.setObjectName("verticalLayout")
        self.fullScreenBtn = QtWidgets.QPushButton(self.tools2D)
        self.fullScreenBtn.setObjectName("allScreenBtn")
        self.verticalLayout.addWidget(self.fullScreenBtn)
        self.checkBoxAlignment = QtWidgets.QCheckBox(self.tools2D)
        self.checkBoxAlignment.setObjectName("checkBoxAlignment")
        self.verticalLayout.addWidget(self.checkBoxAlignment)
        self.checkBoxCoordinates = QtWidgets.QCheckBox(self.tools2D)
        self.checkBoxCoordinates.setObjectName("checkBoxCoordinates")
        self.verticalLayout.addWidget(self.checkBoxCoordinates)
        self.preview2D = QtWidgets.QGraphicsView(self.centralwidget)
        self.preview2D.setGeometry(QtCore.QRect(10, 10, 256, 192))
        self.preview2D.setObjectName("preview2D")
        self.preview3D = QtWidgets.QGraphicsView(self.centralwidget)
        self.preview3D.setGeometry(QtCore.QRect(285, 10, 861, 521))
        self.preview3D.setObjectName("preview3D")
        self.tools3D = QtWidgets.QGroupBox(self.centralwidget)
        self.tools3D.setGeometry(QtCore.QRect(280, 550, 871, 151))
        self.tools3D.setObjectName("tools3D")
        self.mouseXYTextEdit = QtWidgets.QTextEdit(self.tools3D)
        self.mouseXYTextEdit.setGeometry(QtCore.QRect(10, 40, 191, 31))
        self.mouseXYTextEdit.setObjectName("mouseXYTextEdit")
        self.label_3 = QtWidgets.QLabel(self.tools3D)
        self.label_3.setGeometry(QtCore.QRect(10, 20, 101, 16))
        self.label_3.setObjectName("label_3")
        self.findStarBtn = QtWidgets.QPushButton(self.tools3D)
        self.findStarBtn.setGeometry(QtCore.QRect(10, 80, 113, 32))
        self.findStarBtn.setObjectName("findStarBtn")
        self.closestStarTextBrowser = QtWidgets.QTextBrowser(self.tools3D)
        self.closestStarTextBrowser.setGeometry(QtCore.QRect(235, 30, 621, 111))
        self.closestStarTextBrowser.setObjectName("closestStarTextBrowser")
        self.resetBtn = QtWidgets.QPushButton(self.centralwidget)
        self.resetBtn.setGeometry(QtCore.QRect(10, 450, 251, 32))
        self.resetBtn.setObjectName("resetBtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1231, 22))
        self.menubar.setObjectName("menubar")
        self.menuSaveAs = QtWidgets.QMenu(self.menubar)
        self.menuSaveAs.setObjectName("menuSaveAs")
        self.menuStarStandard = QtWidgets.QMenu(self.menubar)
        self.menuStarStandard.setObjectName("menuStarStandard")
        self.menuDataset = QtWidgets.QMenu(self.menubar)
        self.menuDataset.setObjectName("menuDataset")
        self.menuBackground = QtWidgets.QMenu(self.menubar)
        self.menuBackground.setObjectName("menuBackground")
        MainWindow.setMenuBar(self.menubar)
        self.actionpng = QtWidgets.QAction(MainWindow)
        self.actionpng.setObjectName("actionpng")
        self.actionjpeg = QtWidgets.QAction(MainWindow)
        self.actionjpeg.setObjectName("actionjpeg")
        self.actionsvg = QtWidgets.QAction(MainWindow)
        self.actionsvg.setObjectName("actionsvg")
        self.action1 = QtWidgets.QAction(MainWindow)
        self.action1.setObjectName("action1")
        self.action2 = QtWidgets.QAction(MainWindow)
        self.action2.setObjectName("action2")
        self.action3 = QtWidgets.QAction(MainWindow)
        self.action3.setObjectName("action3")
        self.action4 = QtWidgets.QAction(MainWindow)
        self.action4.setObjectName("action4")
        self.actionNo_1 = QtWidgets.QAction(MainWindow)
        self.actionNo_1.setObjectName("actionNo_1")
        self.actionNo_2 = QtWidgets.QAction(MainWindow)
        self.actionNo_2.setObjectName("actionNo_2")
        self.actionNo_3 = QtWidgets.QAction(MainWindow)
        self.actionNo_3.setObjectName("actionNo_3")
        self.actionNo_4 = QtWidgets.QAction(MainWindow)
        self.actionNo_4.setObjectName("actionNo_4")
        self.action_background = QtWidgets.QAction(MainWindow)
        self.action_background.setObjectName("action_background")
        self.actionNatural = QtWidgets.QAction(MainWindow)
        self.actionNatural.setObjectName("actionNatural")
        self.actionPrinterGreyscale = QtWidgets.QAction(MainWindow)
        self.actionPrinterGreyscale.setObjectName("actionPrinterGreyscale")
        self.actionPrinterFriendly = QtWidgets.QAction(MainWindow)
        self.actionPrinterFriendly.setObjectName("actionPrinterFriendly")
        self.actionGreyscale = QtWidgets.QAction(MainWindow)
        self.actionGreyscale.setObjectName("actionGreyscale")
        self.actionPurpleSky = QtWidgets.QAction(MainWindow)
        self.actionPurpleSky.setObjectName("actionPurpleSky")
        self.menuSaveAs.addAction(self.actionpng)
        self.menuSaveAs.addAction(self.actionjpeg)
        self.menuSaveAs.addAction(self.actionsvg)
        self.menuStarStandard.addAction(self.action1)
        self.menuStarStandard.addAction(self.action2)
        self.menuStarStandard.addAction(self.action3)
        self.menuStarStandard.addAction(self.action4)
        self.menuDataset.addAction(self.actionNo_1)
        self.menuDataset.addAction(self.actionNo_2)
        self.menuDataset.addAction(self.actionNo_3)
        self.menuDataset.addAction(self.actionNo_4)
        self.menuBackground.addAction(self.actionNatural)
        self.menuBackground.addAction(self.actionPrinterGreyscale)
        self.menuBackground.addAction(self.actionPrinterFriendly)
        self.menuBackground.addAction(self.actionGreyscale)
        self.menuBackground.addAction(self.actionPurpleSky)
        self.menubar.addAction(self.menuDataset.menuAction())
        self.menubar.addAction(self.menuStarStandard.menuAction())
        self.menubar.addAction(self.menuSaveAs.menuAction())
        self.menubar.addAction(self.menuBackground.menuAction())
        # self.fullScreenBtn.clicked.connect(MainWindow.hello)
        # self.pushButton.clicked.connect(MainWindow.hello)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "仰望"))
        self.tools2D.setTitle(_translate("MainWindow", "二维图选项"))
        self.fullScreenBtn.setText(_translate("MainWindow", "全屏展示二维图"))
        self.checkBoxAlignment.setText(_translate("MainWindow", "有准线"))
        self.checkBoxCoordinates.setText(_translate("MainWindow", "有坐标"))
        self.tools3D.setTitle(_translate("MainWindow", "鼠标点击三维空间，找到附近的星星"))
        self.label_3.setText(_translate("MainWindow", "你点击的位置是："))
        self.findStarBtn.setText(_translate("MainWindow", "最近的星体"))
        self.resetBtn.setText(_translate("MainWindow", "清空结果"))
        self.menuSaveAs.setTitle(_translate("MainWindow", "2D预览另存为"))
        self.menuStarStandard.setTitle(_translate("MainWindow", "星等"))
        self.menuDataset.setTitle(_translate("MainWindow", " 导入数据集"))
        self.menuBackground.setTitle(_translate("MainWindow", "背景色"))
        self.actionpng.setText(_translate("MainWindow", "png"))
        self.actionjpeg.setText(_translate("MainWindow", "jpeg"))
        self.actionsvg.setText(_translate("MainWindow", "svg"))
        self.action1.setText(_translate("MainWindow", "1"))
        self.action2.setText(_translate("MainWindow", "2"))
        self.action3.setText(_translate("MainWindow", "3"))
        self.action4.setText(_translate("MainWindow", "4"))
        self.actionNo_1.setText(_translate("MainWindow", "No.1"))
        self.actionNo_2.setText(_translate("MainWindow", "No.2"))
        self.actionNo_3.setText(_translate("MainWindow", "No.3"))
        self.actionNo_4.setText(_translate("MainWindow", "No.4"))
        self.action_background.setText(_translate("MainWindow", "背景色"))
        self.actionNatural.setText(_translate("MainWindow", "Natural"))
        self.actionPrinterGreyscale.setText(_translate("MainWindow", "Printer greyscale"))
        self.actionPrinterFriendly.setText(_translate("MainWindow", "Printer friendly"))
        self.actionGreyscale.setText(_translate("MainWindow", "Greyscale"))
        self.actionPurpleSky.setText(_translate("MainWindow", "Purple sky"))

    def get2DFullScreen(self):
        if (self.fullScreenBtn.)

