# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LookUp2TheStars(object):
    def setupUi(self, LookUp2TheStars):
        LookUp2TheStars.setObjectName("LookUp2TheStars")
        LookUp2TheStars.resize(1231, 755)
        self.centralwidget = QtWidgets.QWidget(LookUp2TheStars)
        self.centralwidget.setObjectName("centralwidget")
        self.tools2D = QtWidgets.QGroupBox(self.centralwidget)
        self.tools2D.setGeometry(QtCore.QRect(10, 207, 251, 241))
        self.tools2D.setObjectName("tools2D")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tools2D)
        self.verticalLayout.setObjectName("verticalLayout")
        self.fullScreenBtn = QtWidgets.QPushButton(self.tools2D)
        self.fullScreenBtn.setObjectName("fullScreenBtn")
        self.verticalLayout.addWidget(self.fullScreenBtn)
        self.alignmentLinesCheckBox = QtWidgets.QCheckBox(self.tools2D)
        self.alignmentLinesCheckBox.setObjectName("alignmentLinesCheckBox")
        self.verticalLayout.addWidget(self.alignmentLinesCheckBox)
        self.coordinatesCheckBox = QtWidgets.QCheckBox(self.tools2D)
        self.coordinatesCheckBox.setObjectName("coordinatesCheckBox")
        self.verticalLayout.addWidget(self.coordinatesCheckBox)
        self.preview2D = QtWidgets.QGraphicsView(self.centralwidget)
        self.preview2D.setGeometry(QtCore.QRect(10, 10, 256, 192))
        self.preview2D.setObjectName("preview2D")
        self.tools3D = QtWidgets.QGroupBox(self.centralwidget)
        self.tools3D.setGeometry(QtCore.QRect(280, 550, 871, 151))
        self.tools3D.setObjectName("tools3D")
        self.mouseXYTextEdit = QtWidgets.QTextEdit(self.tools3D)
        self.mouseXYTextEdit.setGeometry(QtCore.QRect(10, 40, 191, 31))
        self.mouseXYTextEdit.setObjectName("mouseXYTextEdit")
        self.label_3 = QtWidgets.QLabel(self.tools3D)
        self.label_3.setGeometry(QtCore.QRect(10, 20, 101, 16))
        self.label_3.setObjectName("label_3")
        self.findStarBtn = QtWidgets.QPushButton(self.tools3D)
        self.findStarBtn.setGeometry(QtCore.QRect(10, 80, 113, 32))
        self.findStarBtn.setObjectName("findStarBtn")
        self.closestStarTextBrowser = QtWidgets.QTextBrowser(self.tools3D)
        self.closestStarTextBrowser.setGeometry(QtCore.QRect(235, 30, 621, 111))
        self.closestStarTextBrowser.setObjectName("closestStarTextBrowser")
        self.checkBox = QtWidgets.QCheckBox(self.tools3D)
        self.checkBox.setGeometry(QtCore.QRect(20, 120, 86, 20))
        self.checkBox.setObjectName("checkBox")
        self.resetBtn = QtWidgets.QPushButton(self.centralwidget)
        self.resetBtn.setGeometry(QtCore.QRect(10, 450, 251, 32))
        self.resetBtn.setObjectName("resetBtn")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(290, 10, 861, 531))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        LookUp2TheStars.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(LookUp2TheStars)
        self.statusbar.setObjectName("statusbar")
        LookUp2TheStars.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(LookUp2TheStars)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1231, 22))
        self.menubar.setObjectName("menubar")
        self.menuSaveAs = QtWidgets.QMenu(self.menubar)
        self.menuSaveAs.setObjectName("menuSaveAs")
        self.menuStarStandard = QtWidgets.QMenu(self.menubar)
        self.menuStarStandard.setObjectName("menuStarStandard")
        self.menuDataset = QtWidgets.QMenu(self.menubar)
        self.menuDataset.setObjectName("menuDataset")
        self.backgroundMenu = QtWidgets.QMenu(self.menubar)
        self.backgroundMenu.setObjectName("backgroundMenu")
        LookUp2TheStars.setMenuBar(self.menubar)
        self.actionpng = QtWidgets.QAction(LookUp2TheStars)
        self.actionpng.setObjectName("actionpng")
        self.actionjpeg = QtWidgets.QAction(LookUp2TheStars)
        self.actionjpeg.setObjectName("actionjpeg")
        self.actionsvg = QtWidgets.QAction(LookUp2TheStars)
        self.actionsvg.setObjectName("actionsvg")
        self.action1 = QtWidgets.QAction(LookUp2TheStars)
        self.action1.setObjectName("action1")
        self.action2 = QtWidgets.QAction(LookUp2TheStars)
        self.action2.setObjectName("action2")
        self.action3 = QtWidgets.QAction(LookUp2TheStars)
        self.action3.setObjectName("action3")
        self.action4 = QtWidgets.QAction(LookUp2TheStars)
        self.action4.setObjectName("action4")
        self.actionBSC = QtWidgets.QAction(LookUp2TheStars)
        self.actionBSC.setObjectName("actionBSC")
        self.actionHipparcos = QtWidgets.QAction(LookUp2TheStars)
        self.actionHipparcos.setObjectName("actionHipparcos")
        self.actionNatrual = QtWidgets.QAction(LookUp2TheStars)
        self.actionNatrual.setObjectName("actionNatrual")
        self.actionPurple_sky = QtWidgets.QAction(LookUp2TheStars)
        self.actionPurple_sky.setObjectName("actionPurple_sky")
        self.actionGreyscale = QtWidgets.QAction(LookUp2TheStars)
        self.actionGreyscale.setObjectName("actionGreyscale")
        self.actionPrinter_friendly = QtWidgets.QAction(LookUp2TheStars)
        self.actionPrinter_friendly.setObjectName("actionPrinter_friendly")
        self.actionPrinter_greyscale = QtWidgets.QAction(LookUp2TheStars)
        self.actionPrinter_greyscale.setObjectName("actionPrinter_greyscale")
        self.menuSaveAs.addAction(self.actionpng)
        self.menuSaveAs.addAction(self.actionjpeg)
        self.menuSaveAs.addAction(self.actionsvg)
        self.menuStarStandard.addAction(self.action1)
        self.menuStarStandard.addAction(self.action2)
        self.menuStarStandard.addAction(self.action3)
        self.menuStarStandard.addAction(self.action4)
        self.menuDataset.addAction(self.actionBSC)
        self.menuDataset.addAction(self.actionHipparcos)
        self.backgroundMenu.addAction(self.actionNatrual)
        self.backgroundMenu.addAction(self.actionPurple_sky)
        self.backgroundMenu.addAction(self.actionGreyscale)
        self.backgroundMenu.addAction(self.actionPrinter_friendly)
        self.backgroundMenu.addAction(self.actionPrinter_greyscale)
        self.menubar.addAction(self.menuDataset.menuAction())
        self.menubar.addAction(self.menuStarStandard.menuAction())
        self.menubar.addAction(self.menuSaveAs.menuAction())
        self.menubar.addAction(self.backgroundMenu.menuAction())

        self.retranslateUi(LookUp2TheStars)
        QtCore.QMetaObject.connectSlotsByName(LookUp2TheStars)

    def retranslateUi(self, LookUp2TheStars):
        _translate = QtCore.QCoreApplication.translate
        LookUp2TheStars.setWindowTitle(_translate("LookUp2TheStars", "仰望"))
        self.tools2D.setTitle(_translate("LookUp2TheStars", "二维图选项"))
        self.fullScreenBtn.setText(_translate("LookUp2TheStars", "全屏展示二维图"))
        self.alignmentLinesCheckBox.setText(_translate("LookUp2TheStars", "有准线"))
        self.coordinatesCheckBox.setText(_translate("LookUp2TheStars", "有坐标"))
        self.tools3D.setTitle(_translate("LookUp2TheStars", "鼠标点击三维空间，找到附近的星星"))
        self.label_3.setText(_translate("LookUp2TheStars", "你点击的位置是："))
        self.findStarBtn.setText(_translate("LookUp2TheStars", "最近的星体"))
        self.checkBox.setText(_translate("LookUp2TheStars", " 显示地球"))
        self.resetBtn.setText(_translate("LookUp2TheStars", "清空结果"))
        self.menuSaveAs.setTitle(_translate("LookUp2TheStars", "2D预览另存为"))
        self.menuStarStandard.setTitle(_translate("LookUp2TheStars", "星等"))
        self.menuDataset.setTitle(_translate("LookUp2TheStars", " 导入数据集"))
        self.backgroundMenu.setTitle(_translate("LookUp2TheStars", "背景颜色"))
        self.actionpng.setText(_translate("LookUp2TheStars", "png"))
        self.actionjpeg.setText(_translate("LookUp2TheStars", "jpeg"))
        self.actionsvg.setText(_translate("LookUp2TheStars", "svg"))
        self.action1.setText(_translate("LookUp2TheStars", "1"))
        self.action2.setText(_translate("LookUp2TheStars", "2"))
        self.action3.setText(_translate("LookUp2TheStars", "3"))
        self.action4.setText(_translate("LookUp2TheStars", "4"))
        self.actionBSC.setText(_translate("LookUp2TheStars", "BSC"))
        self.actionBSC.setIconText(_translate("LookUp2TheStars", "BSC"))
        self.actionHipparcos.setText(_translate("LookUp2TheStars", "Hipparcos"))
        self.actionNatrual.setText(_translate("LookUp2TheStars", "Natrual"))
        self.actionPurple_sky.setText(_translate("LookUp2TheStars", "Purple sky"))
        self.actionGreyscale.setText(_translate("LookUp2TheStars", "Greyscale"))
        self.actionPrinter_friendly.setText(_translate("LookUp2TheStars", "Printer friendly"))
        self.actionPrinter_greyscale.setText(_translate("LookUp2TheStars", "Printer greyscale"))


